### ISSUE TITLE
 Share types

### ISSUE THREAD

**Issue by habibGamal** [adonisjs/inertia#13]
### Package version

current version

### Describe the bug

export default class CategoriesController {
  public async index({ inertia }: HttpContext) {
    const data = {id:5};
    return inertia.render('RenderModel', data)
  }
....

import type { InferPageProps } from '@adonisjs/inertia/types'
import type CategoriesController from '#controllers/categories_controller'

type Props = InferPageProps<CategoriesController, 'index'>

and Props is any!!!

**Comment by Julien-R44** [comment]
Please try the following. Go to `inertia/app/app.tsx` file and add this : 

```ts
/// <reference path="../../adonisrc.ts" />
```

**Comment by habibGamal** [comment]
it works fine

**Comment by Julien-R44** [comment]
Lemme add it to the documentation :) 
Thanks
