### ISSUE TITLE
is there is somthing equivalent to ziggy-js for routing

### ISSUE THREAD

**Issue by habibGamal** [adonisjs/inertia#14]
### Package version

current version

### Describe the bug

- backend
router.get('posts',/* ... */).as('posts.index');
- frontend
route('posts.index');

**Comment by Julien-R44** [comment]
not yet, but i've started working on it. soon™️ :smile:

**Comment by axelvaindal** [comment]
Hey @Julien-R44 👋

I've been redirected here from the Discord, and I'm really interested in supporting global helpers with Inertia.

Will the scope of your work only be on routing, or also on other helpers such as i18n and assets ?

Thanks for your work 🙏

**Comment by Julien-R44** [comment]
Can you open 2 different issues to explain what are you expecting as helpers for i18n and assets? 
about i18n I think I can see pretty much, but not sure about the assets

Thanks

**Comment by axelvaindal** [comment]
> Can you open 2 different issues to explain what are you expecting as helpers for i18n and assets? about i18n I think I can see pretty much, but not sure about the assets
> 
> Thanks

I've opened an issue regarding i18n, but after a good night sleep I guess I don't need anything for assets as I can import them directly into the React component.

https://github.com/adonisjs/inertia/issues/21

**Comment by lncitador** [comment]
i don't know how the work with this functionality is going, but i had something i used in projects that was just a commando, but after i learned about hooks i decided to create a library based on ziggy and stardust and stop duplicating code in these two jobs, it's still in prerelease.

https://github.com/izzyjs/route#readme

**Comment by Julien-R44** [comment]
"Tuyau" is out : https://github.com/Julien-R44/tuyau
Documentation : https://tuyau.julr.dev/

Basically, it allows you to do a lot of things. I'll let you discover the documentation. But among other things, the Tuyau client includes [helpers similar to those in ziggy](https://tuyau.julr.dev/docs/client#generating-url), and a [typesafe `Link` component for Inertia.](https://tuyau.julr.dev/docs/inertia)

Later we should probably have a typesafe `useForm` for Inertia.

Let me know if it works for you :)
