### ISSUE TITLE
@inertiaHead use wrong type to render `head` from inertia output

### ISSUE THREAD

**Issue by Bricklou** [adonisjs/inertia#15]
### Package version

1.0.0-23

### Describe the bug

The `@inertiaHeads` tag is not properly implemented here: https://github.com/adonisjs/inertia/blob/2d697a7f363b23575d5eab96bc5a1d92a08db3f6/src/server_renderer.ts#L34

Instead of `Promise<{ head: string; body: string }>`, it should be `Promise<{ head: string[]; body: string }>` like we can see it in the links below:
- https://github.com/inertiajs/inertia/blob/29b8a04bb673b148b4d0e2220b088acd53c0ee72/packages/react/src/createInertiaApp.ts#L51
- https://github.com/inertiajs/inertia/blob/29b8a04bb673b148b4d0e2220b088acd53c0ee72/packages/vue3/src/createInertiaApp.ts#L30

**Comment by Julien-R44** [comment]
Should be good with 1.0.0-24

Thanks for the feedback
