### ISSUE TITLE
InferPageProps not exported

### ISSUE THREAD

**Issue by Xstoudi** [adonisjs/inertia#17]
### Package version

1.0.0-25

### Describe the bug

The [doc mentions](https://docs.adonisjs.com/guides/inertia#share-types) this code:
```ts
import { InferPageProps } from '@adonisjs/inertia'
```

but:
> TS2305: Module '@adonisjs/inertia' has no exported member InferPageProps

**Comment by Julien-R44** [comment]
This is a documentation issue, type is available from `@adonisjs/inertia/types`

Fixed here https://github.com/adonisjs/v6-docs/commit/1a607bd367db7c1f57f5d00b30452732a73683ed
