### ISSUE TITLE
InferPageProps doesn't work for me 

### ISSUE THREAD

**Issue by loiclaborderie** [adonisjs/inertia#22]
### Package version

v1.0.0-28

### Describe the bug

Hello,

I'm using Inertia with AdonisJS 6 and I wanna use either Vue or React, but either way my issue is that my props are always wrongly typed using InferPageProps.

```
import { InferPageProps } from '@adonisjs/inertia/types'
import type PropertiesController from '#controllers/properties_controller'

export default function Home(props: InferPageProps<PropertiesController, 'index'>) {
  const { properties } = props
  console.log(props)
  return (
    <>
      <div className="container">
        <p>{props.properties}</p>
        <div className="title">AdonisJS x Inertia x React</div>

        <span>
          Learn more about AdonisJS and Inertia.js by visiting the{' '}
          <a href="https://docs.adonisjs.com/guides/inertia">AdonisJS documentation</a>.
        </span>
      </div>
    </>
  )
}  

// And in my PropertiesController
async index({ request, inertia }: HttpContext) {
    const properties = await PropertyService.getFiltered(request.qs())
    console.log(properties)
    return inertia.render('home', { properties })
  }

```

However, when I try to use my props in the tsx, I got the following error : Property 'properties' does not exist on type '{ [x: number]: any; }'.ts(2339)

I'm using the official AdonisJS extension of Julien, however I'm on vscode, maybe it's only typesafe on other IDE's, I'm not sure, I tried really hard to find other infos but it seems pretty straightforward so maybe I configured something wrong ? 

Thanks for the help guys ! Love all the team !

### Reproduction repo

https://github.com/loiclaborderie/rumahjogja_monorepo

**Comment by Julien-R44** [comment]
Hello

Check the docs, it explains everything. The reference directive, and also the non-type-safe serialization of lucid models: https://docs.adonisjs.com/guides/inertia#types-sharing

Also this issue: https://github.com/adonisjs/inertia/issues/18
