### ISSUE TITLE
[vite] Pre-transform error. Tries to find TSX files in production build, with wrong url

### ISSUE THREAD

**Issue by AlexandreLemoine40** [adonisjs/inertia#27]
### Package version

@adonisjs/inertia@1.1.0

### Describe the bug

<img width="1165" alt="Capture d’écran 2024-06-25 à 13 58 31" src="https://github.com/adonisjs/inertia/assets/47149440/f380d86c-6b49-43ce-b549-10c9f9fb24d2">

Just basically created an Inertia project working perfectly in Dev mode but the production build is wrong, as it tries to find /inertia/..... in the project but inertia folder is not in the production build.

I've also removed inertia folder from the exclude path in the tsconfig but didn't change the result

**Comment by RomainLanz** [comment]
Hey @AlexandreLemoine40! 👋🏻 

Have you correctly set your `NODE_ENV` variable to `production`?

**Comment by AlexandreLemoine40** [comment]
Hey @RomainLanz,
Yes, as stated in the docs https://docs.adonisjs.com/guides/views-and-templates/inertia#why-my-production-build-is-not-working-

I'd really like to make it work as I'm a big fan of Adonis framework.

And btw there are other production build incoherences I'll raise issues for, concerning Lucid/Luxon imports builds

**Comment by AlexandreLemoine40** [comment]
Ok I'll downgrade TS and test again.

For the initial problem I just created my project using `npm init adonisjs@latest my-project`, and chose Inertia, TS, React, and Session auth. Ran the migrations to my database, ran npm build, cd build, npm ci omit command, and npm start. That's all.

**Comment by Julien-R44** [comment]
It's pretty sure that you don't have NODE_ENV to `production`. 
![image](https://github.com/adonisjs/inertia/assets/8337858/e081ef02-ecad-41de-8a37-5b0b72af887e)

This message comes from the Vite dev server when it starts up. Which means you don't have NODE_ENV at production

**Comment by AlexandreLemoine40** [comment]
<img width="325" alt="Capture d’écran 2024-06-25 à 14 30 09" src="https://github.com/adonisjs/inertia/assets/47149440/3ff8cc78-4b6b-469c-aae3-8646e297e903">

my .env is in the build directory.

and still has the same effect
<img width="922" alt="Capture d’écran 2024-06-25 à 14 31 05" src="https://github.com/adonisjs/inertia/assets/47149440/1778608d-c163-42dc-98c5-51e8eed8f103">

**Comment by AlexandreLemoine40** [comment]
Needed to pass NODE_ENV=production in the `node bin/server.js` command line as `NODE_ENV=production node bin/server.js`
