### ISSUE TITLE
In Inertia starter kit, making any changes to the app.css throws "css hmr is not supported" error

### ISSUE THREAD

**Issue by IcyFoxe** [adonisjs/inertia#31]
### Package version

1.1.0

### Describe the bug

I've been testing out Inertia with Vue, and I've noticed, that making any changes to the `inertia\css\app.css` file will throw the `[vite] css hmr is not supported in runtime mode` error in the console, while still reflecting the changes in the browser window. Not sure how to fix this error.

_To reproduce:_
Initialize Adonis app with Inertia Starter Kit, choose Vue adapter, and set server-side rendering with Inertia to `true`. Once the dev server is running, any changes you make to the app.css file will trigger the error.

**Comment by RomainLanz** [comment]
Hey @IcyFoxe! 👋🏻 

It doesn't throw an error. It is a warning made by Vite that we cannot control.
It is not important, and you can just ignore it.

**Comment by IcyFoxe** [comment]
I see. Is there a way to hide this warning? Because it's cluttering the console a lot, especially since sometimes it writes the same message 3+ times in a row after a single save.

**Comment by IcyFoxe** [comment]
I've noticed, that it doesn't happen if I don't touch the refresh button of the page. It works fine without any warnings. However after refreshing the page, it starts appearing. 

It seems that HMR watcher gets duplicated after page refresh, and they probably start conflicting with eachother. Even the warning message appears as many times (+1), as the page was refreshed further proving this conclusion.

After 1 refresh:
![image](https://github.com/user-attachments/assets/4b23d908-c27c-4797-964d-bc261d96b081)

After 3 refreshes:
![image](https://github.com/user-attachments/assets/aa1ccdf7-b175-4358-b5f1-9e7465667d19)

**Comment by Julien-R44** [comment]
Hey

So I never really understood why this message was being displayed, and I couldn’t find much information about it either. And this warning does not seem to cause any particular problems. Everything seems to be working fine.

However, I’ve fixed the issue where the message was duplicated every time you refreshed the page. It will now only display once, no matter how many times you refreshed the page.

I think we can close the issue, and IMO, with Vite 6 and [the Environment API](https://deploy-preview-16471--vite-docs-main.netlify.app/guide/api-environment), it’s very likely that this message will be gone
