### ISSUE TITLE
Inertia is missing from HttpContext when running multiple test suites

### ISSUE THREAD

**Issue by jeppester** [adonisjs/inertia#39]
### Package version

1.2.2

### Describe the bug

When executing multiple test suites after each other (e.g. "functional" and "browser") the inertia property is only available on the HttpContext in the first test suite, but missing in any subsequent suites, leading to `Cannot read properties of undefined (reading 'render')` errors.

I've created a repo to replicate the issue:
https://github.com/jeppester/adonisjs-inertia-test-issue

The repo was created with "npm init adonisjs@latest", choosing inertia, and sqlite.
Afterwards I followed the docs for adding a minimal setup for [httpTests](https://docs.adonisjs.com/guides/testing/http-tests) and [browserTests](https://docs.adonisjs.com/guides/testing/browser-tests)

The issue can be replicated by:
1. Running `node ace test functional` to assert that the functional spec works when executed by itself
2. Running `node ace test browser` to assert that the browser spec works when executed by itself
3. Running the test suites together with `node ace test`, which will lead to a `Cannot read properties of undefined (reading 'render')` due to inertia being missing on the browser context.
4. The order of the test suites can be changed by reordering them in `adonisrc.ts`. The first suite will always succeed whereas the second will fail.

I've investigated the issue a bit and it would seem that the adonisjs app does some cleanup when the first test server is stopped, which it is then not able to recover from when a new test server is started the second test suite.

I think this issue is important to get fixed as it will bite anyone who's goings to build intertia-based apps with both http tests and browser based e2e tests.

### Reproduction repo

https://docs.adonisjs.com/guides/testing/browser-tests

**Comment by Julien-R44** [comment]
Thanks for the reproduction ! It looks more like a TestUtils error than an @adonisjs/inertia error. It seems that middleware are not registered and executed on the second execution of a suite

@thetutlage any ideas? If not, I'll investigate when I've got some time

**Comment by thetutlage** [comment]
Should be fixed by https://github.com/adonisjs/http-server/releases/tag/v7.2.5

Can you please install the latest version of `@adonisjs/core` and then give it a try?

**Comment by jeppester** [comment]
I was about to do some more investigation myself, but I can see that you've already fixed the issue in the meantime :smile:.
I have just tested both my reproduction repo and the other project I discovered the issue on... aaand it works now! :partying_face: 

Thank you for your quick response!
