### ISSUE TITLE
Support InertiaJS 2

### ISSUE THREAD

**Issue by Julien-R44** [adonisjs/inertia#40]
InertiaJS 2 is currently in beta, with quite a few cool new features: https://v2.inertiajs.com/

We need to support this new version asap :)  
Work has already started on the https://github.com/adonisjs/inertia/tree/2.x branch

We'll be using a major new version of @adonisjs/inertia, but we don't expect any breaking changes backend-side.

**Comment by Julien-R44** [comment]
Beta version released. See release notes https://github.com/adonisjs/inertia/releases/tag/v2.0.0-beta.0

**Comment by dunhamjared** [comment]
The stable version of Interia.js 2.0 just dropped! :) 
https://github.com/inertiajs/inertia/releases/tag/v2.0.0

**Comment by Julien-R44** [comment]
Stable release : https://github.com/adonisjs/inertia/releases/tag/v2.1.0
