### ISSUE TITLE
inertia starter svelte currently broken

### ISSUE THREAD

**Issue by munxar** [adonisjs/inertia#48]
### Package version

@adonisjs/inertia@1.2.3

### Describe the bug

Hello

I run the following scaffold command:
`npm init adonisjs@latest hello-world`

Choices:

- Inertia Starter Kit
- session
- sqlite
- svelte
- no ssr

The step "Configure Inertia"
Gives a green message (should be an error?):
**Unable to configure "@adonisjs/inertia"**

Running `npm run dev` gives the following error:
```
failed to load config from xxx/hello-world/vite.config.ts

   Error: Cannot find package '@sveltejs/vite-plugin-svelte' imported from
  xxx/hello-world/vite.config.ts.timestamp-1732681947487-f10af5b4b1254.mjs
  ```
  
I run this with node v22.11.0 on an arm mac m2.

**Comment by Barabasbalazs** [comment]
Hey @munxar I think this issue should be reported on the [starter kit repo](https://github.com/adonisjs/inertia-starter-kit), and not on the inertia adapter one.

**Comment by munxar** [comment]
@Barabasbalazs ahh silly me, thank you.
